### ISSUE TITLE
채점기가 있었으면 좋겠습니다

### ISSUE THREAD

**Issue by AirHorizons** [jeuxdeau/maratangs#13]
채점기 템플릿 같은 게 있으면은 간단한 문제들에 대해서 쉽게 답을 구할 수 있을 것 같은데 혹시 템플릿을 어떻게 구현하는지 도움을 주실 분 있습니까?

**Comment by jeuxdeau** [comment]
자쓰가리우것든만가니 (모던하고 빈티지한 느낌으로 만들어주세요)
