### ISSUE TITLE
Questions about 190626 HW

### ISSUE THREAD

**Issue by pullup-dip-burpee** [jeuxdeau/maratangs#14]
1. argument 에 없는 건 전역변수로 만들어져 있다고 가정해서 하나여 아니면 지역변수로 만들어서 쓰나여
2. main함수 만들어도 괜찮나여

**Comment by AirHorizons** [comment]
1 번 질문은 무슨 뜻인지 잘 모르겠지만 2번 질문은 main함수를 만드는 것보다 다른 cpp file에서 main함수를 넣고 테스트를 돌리는 게 더 있어보일 것 같은 기분이... ㅋㅋ

**Comment by pullup-dip-burpee** [comment]
아 1번질문은 잘못했넴
2번은 그럼 별도의 헤더파일을 하나 더 만든다고 생각하믄 댐??

**Comment by jeuxdeau** [comment]
1. 추가했습니다.
2. 편하실 대로...
